workflows:
  android-apk:
    name: Build APK with Auto Signing
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      android:
        app_bundle: false
        apk: true
